
fastq_files: 
  - /data/shamsaddinisha/chips/fastq/small_kq.fastq
  - /data/shamsaddinisha/chips/fastq/small_kr.fastq
  - /data/shamsaddinisha/chips/fastq/small_ks.fastq
  - /data/shamsaddinisha/chips/fastq/small_kt.fastq
  - /data/shamsaddinisha/chips/fastq/small_ku.fastq
  - /data/shamsaddinisha/chips/fastq/small_kv.fastq
  - /data/shamsaddinisha/chips/fastq/small_kw.fastq
  - /data/shamsaddinisha/chips/fastq/small_kx.fastq
  - /data/shamsaddinisha/chips/fastq/small_ky.fastq
  - /data/shamsaddinisha/chips/fastq/small_kz.fastq
  - /data/shamsaddinisha/chips/fastq/small_la.fastq
  - /data/shamsaddinisha/chips/fastq/small_lb.fastq
  - /data/shamsaddinisha/chips/fastq/small_lc.fastq
  - /data/shamsaddinisha/chips/fastq/small_ld.fastq
  - /data/shamsaddinisha/chips/fastq/small_le.fastq
  - /data/shamsaddinisha/chips/fastq/small_lf.fastq
  - /data/shamsaddinisha/chips/fastq/small_lg.fastq
  - /data/shamsaddinisha/chips/fastq/small_lh.fastq
  - /data/shamsaddinisha/chips/fastq/small_li.fastq
  - /data/shamsaddinisha/chips/fastq/small_lj.fastq
  - /data/shamsaddinisha/chips/fastq/small_lk.fastq
  - /data/shamsaddinisha/chips/fastq/small_ll.fastq
  - /data/shamsaddinisha/chips/fastq/small_lm.fastq
  - /data/shamsaddinisha/chips/fastq/small_ln.fastq
  - /data/shamsaddinisha/chips/fastq/small_lo.fastq
  - /data/shamsaddinisha/chips/fastq/small_lp.fastq
  - /data/shamsaddinisha/chips/fastq/small_lq.fastq
  - /data/shamsaddinisha/chips/fastq/small_lr.fastq
  - /data/shamsaddinisha/chips/fastq/small_ls.fastq
  - /data/shamsaddinisha/chips/fastq/small_lt.fastq
  - /data/shamsaddinisha/chips/fastq/small_lu.fastq
  - /data/shamsaddinisha/chips/fastq/small_lv.fastq
  - /data/shamsaddinisha/chips/fastq/small_lw.fastq
  - /data/shamsaddinisha/chips/fastq/small_lx.fastq
  - /data/shamsaddinisha/chips/fastq/small_ly.fastq
  - /data/shamsaddinisha/chips/fastq/small_lz.fastq
  - /data/shamsaddinisha/chips/fastq/small_ma.fastq
  - /data/shamsaddinisha/chips/fastq/small_mb.fastq
  - /data/shamsaddinisha/chips/fastq/small_mc.fastq
  - /data/shamsaddinisha/chips/fastq/small_md.fastq
  - /data/shamsaddinisha/chips/fastq/small_me.fastq
  - /data/shamsaddinisha/chips/fastq/small_mf.fastq
  - /data/shamsaddinisha/chips/fastq/small_mg.fastq
  - /data/shamsaddinisha/chips/fastq/small_mh.fastq
  - /data/shamsaddinisha/chips/fastq/small_mi.fastq
  - /data/shamsaddinisha/chips/fastq/small_mj.fastq
  - /data/shamsaddinisha/chips/fastq/small_mk.fastq
  - /data/shamsaddinisha/chips/fastq/small_ml.fastq
  - /data/shamsaddinisha/chips/fastq/small_mm.fastq
  - /data/shamsaddinisha/chips/fastq/small_mn.fastq
  - /data/shamsaddinisha/chips/fastq/small_mo.fastq
  - /data/shamsaddinisha/chips/fastq/small_mp.fastq
  - /data/shamsaddinisha/chips/fastq/small_mq.fastq
  - /data/shamsaddinisha/chips/fastq/small_mr.fastq
  - /data/shamsaddinisha/chips/fastq/small_ms.fastq
  - /data/shamsaddinisha/chips/fastq/small_mt.fastq
  - /data/shamsaddinisha/chips/fastq/small_mu.fastq
  - /data/shamsaddinisha/chips/fastq/small_mv.fastq
  - /data/shamsaddinisha/chips/fastq/small_mw.fastq
  - /data/shamsaddinisha/chips/fastq/small_mx.fastq
  - /data/shamsaddinisha/chips/fastq/small_my.fastq
  - /data/shamsaddinisha/chips/fastq/small_mz.fastq
  - /data/shamsaddinisha/chips/fastq/small_na.fastq
  - /data/shamsaddinisha/chips/fastq/small_nb.fastq
  - /data/shamsaddinisha/chips/fastq/small_nc.fastq
  - /data/shamsaddinisha/chips/fastq/small_nd.fastq
  - /data/shamsaddinisha/chips/fastq/small_ne.fastq
  - /data/shamsaddinisha/chips/fastq/small_nf.fastq
  - /data/shamsaddinisha/chips/fastq/small_ng.fastq
  - /data/shamsaddinisha/chips/fastq/small_nh.fastq
  - /data/shamsaddinisha/chips/fastq/small_ni.fastq
  - /data/shamsaddinisha/chips/fastq/small_nj.fastq
  - /data/shamsaddinisha/chips/fastq/small_nk.fastq
  - /data/shamsaddinisha/chips/fastq/small_nl.fastq
  - /data/shamsaddinisha/chips/fastq/small_nm.fastq
  - /data/shamsaddinisha/chips/fastq/small_nn.fastq
  - /data/shamsaddinisha/chips/fastq/small_no.fastq
  - /data/shamsaddinisha/chips/fastq/small_np.fastq
  - /data/shamsaddinisha/chips/fastq/small_nq.fastq
  - /data/shamsaddinisha/chips/fastq/small_nr.fastq
  - /data/shamsaddinisha/chips/fastq/small_ns.fastq
  - /data/shamsaddinisha/chips/fastq/small_nt.fastq
  - /data/shamsaddinisha/chips/fastq/small_nu.fastq
  - /data/shamsaddinisha/chips/fastq/small_nv.fastq
  - /data/shamsaddinisha/chips/fastq/small_nw.fastq
  - /data/shamsaddinisha/chips/fastq/small_nx.fastq
  - /data/shamsaddinisha/chips/fastq/small_ny.fastq
  - /data/shamsaddinisha/chips/fastq/small_nz.fastq
  - /data/shamsaddinisha/chips/fastq/small_oa.fastq
  - /data/shamsaddinisha/chips/fastq/small_ob.fastq
  - /data/shamsaddinisha/chips/fastq/small_oc.fastq
  - /data/shamsaddinisha/chips/fastq/small_od.fastq
  - /data/shamsaddinisha/chips/fastq/small_oe.fastq
  - /data/shamsaddinisha/chips/fastq/small_of.fastq
  - /data/shamsaddinisha/chips/fastq/small_og.fastq
  - /data/shamsaddinisha/chips/fastq/small_oh.fastq
  - /data/shamsaddinisha/chips/fastq/small_oi.fastq
  - /data/shamsaddinisha/chips/fastq/small_oj.fastq
  - /data/shamsaddinisha/chips/fastq/small_ok.fastq
  - /data/shamsaddinisha/chips/fastq/small_ol.fastq
  - /data/shamsaddinisha/chips/fastq/small_om.fastq
  - /data/shamsaddinisha/chips/fastq/small_on.fastq
  - /data/shamsaddinisha/chips/fastq/small_oo.fastq
  - /data/shamsaddinisha/chips/fastq/small_op.fastq
  - /data/shamsaddinisha/chips/fastq/small_oq.fastq
  - /data/shamsaddinisha/chips/fastq/small_or.fastq
  - /data/shamsaddinisha/chips/fastq/small_os.fastq
  - /data/shamsaddinisha/chips/fastq/small_ot.fastq
  - /data/shamsaddinisha/chips/fastq/small_ou.fastq
  - /data/shamsaddinisha/chips/fastq/small_ov.fastq
  - /data/shamsaddinisha/chips/fastq/small_ow.fastq
  - /data/shamsaddinisha/chips/fastq/small_ox.fastq
  - /data/shamsaddinisha/chips/fastq/small_oy.fastq
  - /data/shamsaddinisha/chips/fastq/small_oz.fastq
  - /data/shamsaddinisha/chips/fastq/small_pa.fastq
  - /data/shamsaddinisha/chips/fastq/small_pb.fastq
  - /data/shamsaddinisha/chips/fastq/small_pc.fastq
  - /data/shamsaddinisha/chips/fastq/small_pd.fastq
  - /data/shamsaddinisha/chips/fastq/small_pe.fastq
  - /data/shamsaddinisha/chips/fastq/small_pf.fastq
  - /data/shamsaddinisha/chips/fastq/small_pg.fastq
  - /data/shamsaddinisha/chips/fastq/small_ph.fastq
  - /data/shamsaddinisha/chips/fastq/small_pi.fastq
  - /data/shamsaddinisha/chips/fastq/small_pj.fastq
  - /data/shamsaddinisha/chips/fastq/small_pk.fastq
  - /data/shamsaddinisha/chips/fastq/small_pl.fastq
  - /data/shamsaddinisha/chips/fastq/small_pm.fastq
  - /data/shamsaddinisha/chips/fastq/small_pn.fastq
  - /data/shamsaddinisha/chips/fastq/small_po.fastq
  - /data/shamsaddinisha/chips/fastq/small_pp.fastq
  - /data/shamsaddinisha/chips/fastq/small_pq.fastq
  - /data/shamsaddinisha/chips/fastq/small_pr.fastq
  - /data/shamsaddinisha/chips/fastq/small_ps.fastq
  - /data/shamsaddinisha/chips/fastq/small_pt.fastq
  - /data/shamsaddinisha/chips/fastq/small_pu.fastq
  - /data/shamsaddinisha/chips/fastq/small_pv.fastq
  - /data/shamsaddinisha/chips/fastq/small_pw.fastq
  - /data/shamsaddinisha/chips/fastq/small_px.fastq
  - /data/shamsaddinisha/chips/fastq/small_py.fastq
  - /data/shamsaddinisha/chips/fastq/small_pz.fastq
  - /data/shamsaddinisha/chips/fastq/small_qa.fastq
  - /data/shamsaddinisha/chips/fastq/small_qb.fastq
  - /data/shamsaddinisha/chips/fastq/small_qc.fastq
  - /data/shamsaddinisha/chips/fastq/small_qd.fastq
  - /data/shamsaddinisha/chips/fastq/small_qe.fastq
  - /data/shamsaddinisha/chips/fastq/small_qf.fastq
  - /data/shamsaddinisha/chips/fastq/small_qg.fastq
  - /data/shamsaddinisha/chips/fastq/small_qh.fastq
  - /data/shamsaddinisha/chips/fastq/small_qi.fastq
  - /data/shamsaddinisha/chips/fastq/small_qj.fastq
  - /data/shamsaddinisha/chips/fastq/small_qk.fastq
  - /data/shamsaddinisha/chips/fastq/small_ql.fastq
  - /data/shamsaddinisha/chips/fastq/small_qm.fastq
  - /data/shamsaddinisha/chips/fastq/small_qn.fastq
  - /data/shamsaddinisha/chips/fastq/small_qo.fastq
  - /data/shamsaddinisha/chips/fastq/small_qp.fastq
  - /data/shamsaddinisha/chips/fastq/small_qq.fastq
  - /data/shamsaddinisha/chips/fastq/small_qr.fastq
  - /data/shamsaddinisha/chips/fastq/small_qs.fastq
  - /data/shamsaddinisha/chips/fastq/small_qt.fastq
  - /data/shamsaddinisha/chips/fastq/small_qu.fastq
  - /data/shamsaddinisha/chips/fastq/small_qv.fastq
  - /data/shamsaddinisha/chips/fastq/small_qw.fastq
  - /data/shamsaddinisha/chips/fastq/small_qx.fastq
  - /data/shamsaddinisha/chips/fastq/small_qy.fastq
  - /data/shamsaddinisha/chips/fastq/small_qz.fastq
  - /data/shamsaddinisha/chips/fastq/small_ra.fastq
  - /data/shamsaddinisha/chips/fastq/small_rb.fastq
  - /data/shamsaddinisha/chips/fastq/small_rc.fastq
  - /data/shamsaddinisha/chips/fastq/small_rd.fastq
  - /data/shamsaddinisha/chips/fastq/small_re.fastq
  - /data/shamsaddinisha/chips/fastq/small_rf.fastq
  - /data/shamsaddinisha/chips/fastq/small_rg.fastq
  - /data/shamsaddinisha/chips/fastq/small_rh.fastq
  - /data/shamsaddinisha/chips/fastq/small_ri.fastq
  - /data/shamsaddinisha/chips/fastq/small_rj.fastq
  - /data/shamsaddinisha/chips/fastq/small_rk.fastq
  - /data/shamsaddinisha/chips/fastq/small_rl.fastq
  - /data/shamsaddinisha/chips/fastq/small_rm.fastq
  - /data/shamsaddinisha/chips/fastq/small_rn.fastq
  - /data/shamsaddinisha/chips/fastq/small_ro.fastq
  - /data/shamsaddinisha/chips/fastq/small_rp.fastq
  - /data/shamsaddinisha/chips/fastq/small_rq.fastq
  - /data/shamsaddinisha/chips/fastq/small_rr.fastq
  - /data/shamsaddinisha/chips/fastq/small_rs.fastq
  - /data/shamsaddinisha/chips/fastq/small_rt.fastq
  - /data/shamsaddinisha/chips/fastq/small_ru.fastq
  - /data/shamsaddinisha/chips/fastq/small_rv.fastq
  - /data/shamsaddinisha/chips/fastq/small_rw.fastq
  - /data/shamsaddinisha/chips/fastq/small_rx.fastq
  - /data/shamsaddinisha/chips/fastq/small_ry.fastq
  - /data/shamsaddinisha/chips/fastq/small_rz.fastq
  - /data/shamsaddinisha/chips/fastq/small_sa.fastq
  - /data/shamsaddinisha/chips/fastq/small_sb.fastq
  - /data/shamsaddinisha/chips/fastq/small_sc.fastq
  - /data/shamsaddinisha/chips/fastq/small_sd.fastq
  - /data/shamsaddinisha/chips/fastq/small_se.fastq
  - /data/shamsaddinisha/chips/fastq/small_sf.fastq
  - /data/shamsaddinisha/chips/fastq/small_sg.fastq
  - /data/shamsaddinisha/chips/fastq/small_sh.fastq
  - /data/shamsaddinisha/chips/fastq/small_si.fastq
  - /data/shamsaddinisha/chips/fastq/small_sj.fastq
  - /data/shamsaddinisha/chips/fastq/small_sk.fastq
  - /data/shamsaddinisha/chips/fastq/small_sl.fastq
  - /data/shamsaddinisha/chips/fastq/small_sm.fastq
  - /data/shamsaddinisha/chips/fastq/small_sn.fastq
  - /data/shamsaddinisha/chips/fastq/small_so.fastq
  - /data/shamsaddinisha/chips/fastq/small_sp.fastq
  - /data/shamsaddinisha/chips/fastq/small_sq.fastq
  - /data/shamsaddinisha/chips/fastq/small_sr.fastq
  - /data/shamsaddinisha/chips/fastq/small_ss.fastq
  - /data/shamsaddinisha/chips/fastq/small_st.fastq
  - /data/shamsaddinisha/chips/fastq/small_su.fastq
  - /data/shamsaddinisha/chips/fastq/small_sv.fastq
  - /data/shamsaddinisha/chips/fastq/small_sw.fastq
  - /data/shamsaddinisha/chips/fastq/small_sx.fastq
  - /data/shamsaddinisha/chips/fastq/small_sy.fastq
  - /data/shamsaddinisha/chips/fastq/small_sz.fastq
  - /data/shamsaddinisha/chips/fastq/small_ta.fastq
  - /data/shamsaddinisha/chips/fastq/small_tb.fastq
  - /data/shamsaddinisha/chips/fastq/small_tc.fastq
  - /data/shamsaddinisha/chips/fastq/small_td.fastq
  - /data/shamsaddinisha/chips/fastq/small_te.fastq
  - /data/shamsaddinisha/chips/fastq/small_tf.fastq
  - /data/shamsaddinisha/chips/fastq/small_tg.fastq
  - /data/shamsaddinisha/chips/fastq/small_th.fastq
  - /data/shamsaddinisha/chips/fastq/small_ti.fastq
  - /data/shamsaddinisha/chips/fastq/small_tj.fastq
  - /data/shamsaddinisha/chips/fastq/small_tk.fastq
  - /data/shamsaddinisha/chips/fastq/small_tl.fastq
  - /data/shamsaddinisha/chips/fastq/small_tm.fastq
  - /data/shamsaddinisha/chips/fastq/small_tn.fastq
  - /data/shamsaddinisha/chips/fastq/small_to.fastq
  - /data/shamsaddinisha/chips/fastq/small_tp.fastq
  - /data/shamsaddinisha/chips/fastq/small_tq.fastq
  - /data/shamsaddinisha/chips/fastq/small_tr.fastq
  - /data/shamsaddinisha/chips/fastq/small_ts.fastq
  - /data/shamsaddinisha/chips/fastq/small_tt.fastq
  - /data/shamsaddinisha/chips/fastq/small_tu.fastq
  - /data/shamsaddinisha/chips/fastq/small_tv.fastq
  - /data/shamsaddinisha/chips/fastq/small_tw.fastq
  - /data/shamsaddinisha/chips/fastq/small_tx.fastq
  - /data/shamsaddinisha/chips/fastq/small_ty.fastq
  - /data/shamsaddinisha/chips/fastq/small_tz.fastq
  - /data/shamsaddinisha/chips/fastq/small_ua.fastq
  - /data/shamsaddinisha/chips/fastq/small_ub.fastq
  - /data/shamsaddinisha/chips/fastq/small_uc.fastq
  - /data/shamsaddinisha/chips/fastq/small_ud.fastq
  - /data/shamsaddinisha/chips/fastq/small_ue.fastq
  - /data/shamsaddinisha/chips/fastq/small_uf.fastq
  - /data/shamsaddinisha/chips/fastq/small_ug.fastq
  - /data/shamsaddinisha/chips/fastq/small_uh.fastq
  - /data/shamsaddinisha/chips/fastq/small_ui.fastq
  - /data/shamsaddinisha/chips/fastq/small_uj.fastq
  - /data/shamsaddinisha/chips/fastq/small_uk.fastq
  - /data/shamsaddinisha/chips/fastq/small_ul.fastq
  - /data/shamsaddinisha/chips/fastq/small_um.fastq
  - /data/shamsaddinisha/chips/fastq/small_un.fastq
  - /data/shamsaddinisha/chips/fastq/small_uo.fastq
  - /data/shamsaddinisha/chips/fastq/small_up.fastq
  - /data/shamsaddinisha/chips/fastq/small_uq.fastq
  - /data/shamsaddinisha/chips/fastq/small_ur.fastq
  - /data/shamsaddinisha/chips/fastq/small_us.fastq
  - /data/shamsaddinisha/chips/fastq/small_ut.fastq
  - /data/shamsaddinisha/chips/fastq/small_uu.fastq
  - /data/shamsaddinisha/chips/fastq/small_uv.fastq
  - /data/shamsaddinisha/chips/fastq/small_uw.fastq
  - /data/shamsaddinisha/chips/fastq/small_ux.fastq
  - /data/shamsaddinisha/chips/fastq/small_uy.fastq
  - /data/shamsaddinisha/chips/fastq/small_uz.fastq
  - /data/shamsaddinisha/chips/fastq/small_va.fastq
  - /data/shamsaddinisha/chips/fastq/small_vb.fastq
  - /data/shamsaddinisha/chips/fastq/small_vc.fastq
  - /data/shamsaddinisha/chips/fastq/small_vd.fastq
  - /data/shamsaddinisha/chips/fastq/small_ve.fastq
  - /data/shamsaddinisha/chips/fastq/small_vf.fastq
  - /data/shamsaddinisha/chips/fastq/small_vg.fastq
  - /data/shamsaddinisha/chips/fastq/small_vh.fastq
  - /data/shamsaddinisha/chips/fastq/small_vi.fastq
  - /data/shamsaddinisha/chips/fastq/small_vj.fastq
  - /data/shamsaddinisha/chips/fastq/small_vk.fastq
  - /data/shamsaddinisha/chips/fastq/small_vl.fastq
  - /data/shamsaddinisha/chips/fastq/small_vm.fastq
  - /data/shamsaddinisha/chips/fastq/small_vn.fastq
  - /data/shamsaddinisha/chips/fastq/small_vo.fastq
  - /data/shamsaddinisha/chips/fastq/small_vp.fastq
  - /data/shamsaddinisha/chips/fastq/small_vq.fastq
  - /data/shamsaddinisha/chips/fastq/small_vr.fastq
  - /data/shamsaddinisha/chips/fastq/small_vs.fastq
  - /data/shamsaddinisha/chips/fastq/small_vt.fastq
  - /data/shamsaddinisha/chips/fastq/small_vu.fastq
  - /data/shamsaddinisha/chips/fastq/small_vv.fastq
  - /data/shamsaddinisha/chips/fastq/small_vw.fastq
  - /data/shamsaddinisha/chips/fastq/small_vx.fastq
  - /data/shamsaddinisha/chips/fastq/small_vy.fastq
  - /data/shamsaddinisha/chips/fastq/small_vz.fastq
  - /data/shamsaddinisha/chips/fastq/small_wa.fastq
  - /data/shamsaddinisha/chips/fastq/small_wb.fastq
  - /data/shamsaddinisha/chips/fastq/small_wc.fastq
  - /data/shamsaddinisha/chips/fastq/small_wd.fastq
  - /data/shamsaddinisha/chips/fastq/small_we.fastq
  - /data/shamsaddinisha/chips/fastq/small_wf.fastq
  - /data/shamsaddinisha/chips/fastq/small_wg.fastq
  - /data/shamsaddinisha/chips/fastq/small_wh.fastq
  - /data/shamsaddinisha/chips/fastq/small_wi.fastq
  - /data/shamsaddinisha/chips/fastq/small_wj.fastq
  - /data/shamsaddinisha/chips/fastq/small_wk.fastq
  - /data/shamsaddinisha/chips/fastq/small_wl.fastq
  - /data/shamsaddinisha/chips/fastq/small_wm.fastq
  - /data/shamsaddinisha/chips/fastq/small_wn.fastq
  - /data/shamsaddinisha/chips/fastq/small_wo.fastq
  - /data/shamsaddinisha/chips/fastq/small_wp.fastq
  - /data/shamsaddinisha/chips/fastq/small_wq.fastq
  - /data/shamsaddinisha/chips/fastq/small_wr.fastq
  - /data/shamsaddinisha/chips/fastq/small_ws.fastq
  - /data/shamsaddinisha/chips/fastq/small_wt.fastq
  - /data/shamsaddinisha/chips/fastq/small_wu.fastq
  - /data/shamsaddinisha/chips/fastq/small_wv.fastq
  - /data/shamsaddinisha/chips/fastq/small_ww.fastq
  - /data/shamsaddinisha/chips/fastq/small_wx.fastq
  - /data/shamsaddinisha/chips/fastq/small_wy.fastq
  - /data/shamsaddinisha/chips/fastq/small_wz.fastq
  - /data/shamsaddinisha/chips/fastq/small_xa.fastq
  - /data/shamsaddinisha/chips/fastq/small_xb.fastq
  - /data/shamsaddinisha/chips/fastq/small_xc.fastq
  - /data/shamsaddinisha/chips/fastq/small_xd.fastq
  - /data/shamsaddinisha/chips/fastq/small_xe.fastq
  - /data/shamsaddinisha/chips/fastq/small_xf.fastq
  - /data/shamsaddinisha/chips/fastq/small_xg.fastq
  - /data/shamsaddinisha/chips/fastq/small_xh.fastq
  - /data/shamsaddinisha/chips/fastq/small_xi.fastq

WDIR: /data/shamsaddinisha/chips/chip_seq_analysis

idx_bt1: /fdb/igenomes/Homo_sapiens/UCSC/hg19/Sequence/BowtieIndex/genome
